"~/.vimrc
" environment
set nocompatible backspace=indent,eol,start history=50 nowrap mouse=a backup scs
set ruler showcmd incsearch hlsearch lbr expandtab tabstop=2 shiftwidth=2 deco
set softtabstop=2 nu wildmenu wildmode=list:longest,full cc=+1 foldmethod=indent
set foldlevel=99 clipboard=unnamed listchars=tab:\|.,trail:. list
set cot=longest,menuone
set backupdir=./.backup,$HOME/.vim/backups,/tmp
set directory=./.backup,$HOME/.vim/backups,/tmp

syntax on
" syntax off
filetype plugin indent on

if &shell =~# 'fish$'
  set shell=bash
endif

" bindings are in a seperate file. there are lots.
source $HOME/.vim/bind.vim

" autocmd stuff
augroup vimrcEx
  au!
  autocmd BufReadPost *
        \ if line("'\"") > 1 && line("'\"") <= line("$")
        \| exe "normal! g`\"" | endif
  autocmd BufRead,BufNewFile *.asciidoc,*.adoc,*.ad
        \ setlocal filetype=asciidoc
  autocmd BufRead,BufNewFile *.md
        \ setlocal filetype=markdown
augroup END

execute pathogen#infect()
let g:SuperTabDefaultCompletionType = "context"
let g:SuperTabLongestEnhanced = 1
let g:SuperTabLongestHighlight = 1

set gfn=Ubuntu\ Mono\ 11 go=

if $COLORTERM == 'gnome-terminal'
  set t_Co=256
endif

if has("gui_running")
  colorscheme molokai
elseif $TERM == 'linux' || $TERM == 'screen'
  colorscheme default
elseif $USER == 'root'
  colorscheme slate
else
  colorscheme cterm
endif
" ## added by OPAM user-setup for vim / base ## d611dd144a5764d46fdea4c0c2e0ba07 ## you can edit, but keep this line
let s:opam_share_dir = system("opam var share")
let s:opam_share_dir = substitute(s:opam_share_dir, '[\r\n]*$', '', '')

let s:opam_configuration = {}

function! OpamConfOcpIndent()
  execute "set rtp^=" . s:opam_share_dir . "/ocp-indent/vim"
endfunction
let s:opam_configuration['ocp-indent'] = function('OpamConfOcpIndent')

function! OpamConfOcpIndex()
  execute "set rtp+=" . s:opam_share_dir . "/ocp-index/vim"
endfunction
let s:opam_configuration['ocp-index'] = function('OpamConfOcpIndex')

function! OpamConfMerlin()
  let l:dir = s:opam_share_dir . "/merlin/vim"
  execute "set rtp+=" . l:dir
endfunction
let s:opam_configuration['merlin'] = function('OpamConfMerlin')

let s:opam_packages = ["ocp-indent", "ocp-index", "merlin"]
let s:opam_available_tools = []
for tool in s:opam_packages
  " Respect package order (merlin should be after ocp-index)
  if isdirectory(s:opam_share_dir . "/" . tool)
    call add(s:opam_available_tools, tool)
    call s:opam_configuration[tool]()
  endif
endfor
" ## end of OPAM user-setup addition for vim / base ## keep this line
" ## added by OPAM user-setup for vim / ocp-indent ## da02e68d8bf62d03acd3b13df7716969 ## you can edit, but keep this line
if count(s:opam_available_tools,"ocp-indent") == 0
  source "/home/ninjaaron/.opam/5.1.1/share/ocp-indent/vim/indent/ocaml.vim"
endif
if count(s:opam_available_tools,"ocp-indent") == 0
  source "/home/ninjaaron/.opam/5.1.1/share/ocp-indent/vim/indent/ocaml.vim"
endif
" ## added by OPAM user-setup for vim / ocp-indent ## 24340a0985257eeba101ce2e8fbdfe80 ## you can edit, but keep this line
if count(s:opam_available_tools,"ocp-indent") == 0
  source "/home/ninjaaron/.opam/5.4.0+flambda/share/ocp-indent/vim/indent/ocaml.vim"
endif
" ## end of OPAM user-setup addition for vim / ocp-indent ## keep this line
