#!/bin/bash
# generates and loads a new ~/.Xresources file based on settings from another file.

# get the settings
theme=$(cat ~/.theme)
font="bitocrafull:pixelsize=10"
source ~/.themes/"$theme"

# write the comments and colors
cat > ~/.Xresources << EOF
! -----------------------------------------------
! $theme_name theme
! file:     ~/.Xresources
! author:   Aaron "ninjaaron" Christianson
! modified: $date_modified
! -----------------------------------------------

! color scheme
*background: #cccccc
*foreground: #222222
URxvt.background: $bg_color
URxvt.foreground: $fg_color
XTerm*background: $bg_color
XTerm*foreground: $fg_color
! Black + DarkGrey
*color0:  $black
*color8:  $dark_grey
! Red
*color1:  $red
*color9:  $light_red 
! Green
*color2:  $green
*color10: $light_green
! Yellow
*color3:  $yellow
*color11: $light_yellow
! Blue
*color4:  $blue
*color12: $light_blue
! Magenta
*color5:  $magenta
*color13: $light_magenta
! Cyan
*color6:  $cyan
*color14: $light_cyan
! LightGrey + White
*color7: $light_grey
*color15: $white
EOF


# add fadding if desired
if [ -n "$fading" ]; then
  cat >> ~/.Xresources << EOF
! fading options
URxvt.fadeColor: $bg_color
URxvt.fading: 50
EOF

fi


# add transparency based on settings
# check if transparency is set
if [ "$transparent" = "true" ];then
  echo "
! transparency settings
URxvt.transparent: true" >> ~/.Xresources 


  #echo correct transparency settings
  if [ -z "$tr_settings" ];then
    echo "URxvt.shading: 20" >> ~/.Xresources
  elif [ "$tr_settings" = "light" ];then
    echo "URxvt.shading: 185" >> ~/.Xresources
  else
    echo "$tr_settings" >> ~/.Xresources
  fi
fi

if [[ -n $Xextra ]];then
  echo "$Xextra" >> ~/.Xresources
fi


# add font and various other universal defaults
cat >> ~/.Xresources << EOF
! font
URxvt.font: xft:$font,xft:Taamey Frank CLM
xterm*faceName: $font
Xft.autohint: 0
Xft.lcdfilter:  lcddefault
Xft.hintstyle:  hintfull
Xft.hinting: 1
Xft.antialias: 1
Xft.rgba: rgb

! scrollbar
URxvt.scrollBar: off

! selection & link handing
URxvt.perl-ext-common:      default,url-select,keyboard-select,clipboard
URxvt.keysym.M-c:   perl:clipboard:copy
URxvt.keysym.M-v:   perl:clipboard:paste
URxvt.url-select.launcher:  firefox
URxvt.url-select.underline: true
URxvt.keysym.M-u:           perl:url-select:select_next
URxvt.keysym.M-Escape:      perl:keyboard-select:activate
URxvt.keysym.M-s:           perl:keyboard-select:search

! fonts to choose
URxvt.keysym.M-C-0: command:\033]710;xft:bitbuntufull:pixelsize=10,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-parenright: command:\033]710;xft:Ubuntu Mono:pixelsize=20,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-1: command:\033]710;xft:bitocrafull:pixelsize=11,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-exclam: command:\033]710;xft:Ubuntu Mono:pixelsize=11:style=bold,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-2: command:\033]710;-*-fixed-medium-r-*-*-12-*,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-at: command:\033]710;xft:Ubuntu Mono:pixelsize=12,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-3: command:\033]710;xft:bitocra13full:pixelsize=13,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-numbersign: command:\033]710;xft:Ubuntu Mono:pixelsize=13,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-4: command:\033]710;-*-terminus-medium-*-*-*14-*,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-dollar: command:\033]710;xft:Ubuntu Mono:pixelsize=14,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-5: command:\033]710;xft:5thElement\007
URxvt.keysym.M-C-percent: command:\033]710;xft:Ubuntu Mono:pixelsize=15,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-6: command:\033]710;xft:5thElementHeb,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-asciicircum: command:\033]710;xft:Ubuntu Mono:pixelsize=16,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-7: command:\033]710;xft:bitocra7,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-ampersand: command:\033]710;xft:Ubuntu Mono:pixelsize=17,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-8: command:\033]710;xft:bitocra7Heb,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-asterisk: command:\033]710;xft:Ubuntu Mono:pixelsize=18,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-parenleft: command:\033]710;xft:Ubuntu Mono:pixelsize=19,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-f: command:\033]710;xft:bigheb:pixelsize=18,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-m: command:\033]710;xft:Ubuntu Mono:pixelsize=34,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-M: command:\033]710;xft:Miriam Mono CLM:pixelsize=34\007
URxvt.keysym.M-C-o: command:\033]710;xft:ocra10:pixelsize=13,xft:Miriam Mono CLM\007
URxvt.keysym.M-C-d: command:\033]710;xft:Dejavu Sans Mono:pixelsize=12:antialias=false,xft:Miriam Mono CLM\007

EOF


# apply the theme
xrdb ~/.Xresources
