#!/usr/bin/env bash

theme=$(cat ~/.theme)
source ~/.themes/"$theme"

cat ~/.i3/base > ~/.config/sway/config

cat >> ~/.config/sway/config << EOF
bindsym \$mod+grave exec swaylock -c 000000
# Style
output HDMI-A-1 bg ~/pic/backs/apocolyps/DD-Post-Apocalyptic-Wallpaper-321.jpg fill
output DP-1     bg ~/pic/backs/apocolyps/DD-Post-Apocalyptic-Wallpaper-151.jpg fill

font pango:${font2:-bitocra 7}
# class                 border  backgr. text    indicator
client.focused          $bg_color ${frame_border_active_color:-$bg_color} ${window_title:-$fg_color} ${window_title:-$fg_color}
client.focused_inactive ${window_border_i:-$bg_color} ${window_border_i:-$bg_color} ${window_title_i:-$dark_grey} $bg_color
client.unfocused        ${window_border_i:-$bg_color} ${window_border_i:-$bg_color} ${window_title_i:-$dark_grey} $bg_color

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
  status_command i3status -c ~/.i3/bar
  position top
  colors {
    background         ${panel_bg:-$bg_color}
    statusline         ${panel_fg:-$fg_color}
    focused_workspace  $bg_color ${panel_fbx:-$black} ${window_title:-$yellow}
    active_workspace   ${panel_fbx:-$black} ${window_border_i:-$bg_color} ${window_title:-$light_grey}
    inactive_workspace ${panel_fbx:-$black} ${window_border_i:-$bg_color} ${panel_fbx:-$black}
    urgent_workspace   $bg_color $bg_color ${panel_alert:-$red}
  }
}


input "2:7:SynPS/2_Synaptics_TouchPad" {
    tap enabled
    natural_scroll enabled
    middle_emulation enabled
    dwt enabled
}
EOF
